### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by michelf** [attaswift/BTree#31]
Tests `BTreeNodeTests.testMakeChildUnique` and `BTreeNodeTests.testEditWithWeakReferences` are failing when I try to run them. (Xcode 9.2 (9C40b))

Is this normal?

**Comment by lorentey** [comment]
Swift 4.0 had a runtime change that broke `isKnownUniquelyReferenced` semantics for objects with weak references. This is fixed in Swift 4.1, restoring the original behavior until a better solution is developed.

Building with Xcode 9.3 resolves the test failures. (See #32)
